#!/usr/bin/env bash
set -euo pipefail

build_dir="${PWD}/out"
project="${PWD##*/}"

usage()
{
    echo "Commands: test, debug, release, run, clean"
}

make_all()
{
    build_type="Debug"
    if [ -n "${1+x}" ]; then
        build_type="$1"
    fi

    cmake -S . -B "${build_dir}" -DCMAKE_BUILD_TYPE="${build_type}" -DMY_PROJECT="${project}"
    cmake --build "${build_dir}" -- all
}

make_clean()
{
    echo ">> Cleaning ${project} <<"
    rm -rf "${build_dir}"
    echo "Removed ${build_dir}"
}

if [ -n "${1+x}" ]; then
    case "$1" in
        "test")
            echo ">> Building ${project} tests <<"
            make_all
            echo ""
            echo ">> Running ${project} tests <<"
            ${build_dir}/bin/tests
            ;;
        "debug")
            echo ">> Building ${project} debug <<"
            make_all
            ;;
        "release")
            make_clean
            echo ""
            echo ">> Building ${project} release <<"
            make_all "Release"
            ;;
        "run")
            target=${build_dir}/bin/${project}
            if [ ! -f "$target" ]; then
                echo ">> Building ${project} debug <<"
                make_all
                echo ""
            fi
            echo ">> Running ${project} <<"
            $target
            ;;
        "clean")
            make_clean
            ;;
        *)
            usage
            ;;
    esac
else
    usage
fi
