#!/usr/bin/env bash
set -euo pipefail

build_dir="./out"
app_name="app"

usage () {
    echo "Commands: test, debug, release, clean"
}

make_all () {
    release="Debug"
    if [ -n "${1+x}" ]; then
        release="$1"
    fi

    cmake -S . -B "${build_dir}" -DCMAKE_BUILD_TYPE=${release}
    cd ./out
    make all
    cd ..
}

make_clean () {
    echo ">> Cleaning ${app_name} <<"
    rm -rf ${build_dir}
    echo "Removed ${build_dir}"
}

if [ -n "${1+x}" ]; then
    case "$1" in
        "test")
            echo ">> Building ${app_name} tests <<"
            make_all
            echo ""
            echo ">> Running ${app_name} tests <<"
            ${build_dir}/test/${app_name}_test
            ;;
        "debug")
            echo ">> Building ${app_name} debug <<"
            make_all
            echo ""
            echo ">> Running ${app_name} debug <<"
            ${build_dir}/src/${app_name}
            ;;
        "release")
            make_clean
            echo ""
            echo ">> Building ${app_name} release <<"
            make_all "Release"
            ;;
        "clean")
            make_clean
            ;;
        *)
            usage
            ;;
    esac
else
    usage
fi
